In [5]:
print("Hello,world!")

Hello,world!

In [8]:
if 5 > 2:
    print("Five is greater than two!")

Five is greater than two!

In [9]:
print("Hello , World !") #This is a comment

Hello , World !

In [11]:
#A program that prints Hello, world! to the screen.

In [12]:
#a program that adds two numbers and prints the result
num1 = 3    
num2 = 5
sum = num1 + num2
print("The sum of", num1, "and", num2, "is", sum)

The sum of 3 and 5 is 8

In [13]:
#python numbers
x = 4
y = 'shahid'
z = 5.987

print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'str'>
<class 'float'>

In [14]:
#integer
x=1458
y=35656222554887711
z=-32555222

print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'int'>
<class 'int'>

In [15]:
#float
x=1.10
y=1.0
z=-35.59    
print(type(x))
print(type(y)) 
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>

In [16]:
#complex
x=3+5j
y=5j    
z=-5j
print(type(x))  
print(type(y))
print(type(z))

<class 'complex'>
<class 'complex'>
<class 'complex'>

In [17]:
#Type conversion
x = 1    # int 
y = 2.8  # float
z = 1j   # complex 
#convert from int to float:
a = float(x)
#convert from float to int:
b = int(y)
#convert from int to complex:
c = complex(x)
print(a)
print(b)
print(c)
print(type(a))
print(type(b))
print(type(c))

1.0
2
(1+0j)
<class 'float'>
<class 'int'>
<class 'complex'>

In [18]:
a= '''this is a very long string span multiple lines'''
print(a)

this is a very long string span multiple lines

In [21]:
#slicing string
b = "Hello, World!" 
print(b[2:5])

llo

In [ ]:
#slicing string from the start
b = "Hello, World!" 
print(b[:5])

Hello

In [ ]:
#slicing string to the end
b = "Hello, World!" 
print(b[2:])

llo, World!

In [19]:
#string replace
a = " Hello, World! "
B=a.replace("H","J")
print(B)

 Jello, World!

In [18]:
#string concatenation
a=" Hello"
b=" World!"
c=a+b
print(c)

 Hello World!

In [17]:
#string concatenation with space
a="Hello"
b="World!"
c=a+" "+b
print(c)

Hello World!

In [16]:
#string formatting
age = 36
txt = "My name is Lisa, and I am {}"
print(txt.format(age))

My name is Lisa, and I am 36

In [6]:
#Lists
L1 = ["apple", "banana", "cherry"]
print(L1)

['apple', 'banana', 'cherry']

In [7]:
#list indexing  and slicing
List = [0,1,2,3,4,5]  
print(List[2:5])
print(List[:4])

[2, 3, 4]
[0, 1, 2, 3]

In [8]:
list = [1,2,3,4,5,6,7]
print(list[0])
print(list[1])
print(list[2])
print(list[3])
#slicing the elements
print(list[0:6]) #by default the index value is 0 so  it starts from the other element and go for index -1
print(list[:])
print(list[2:5])
print (list[1:6:2])

1
2
3
4
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]
[3, 4, 5]
[2, 4, 6]

In [9]:
#Negative indexing
List=[1,2,3,4,5]
print(List[-1])
print(List[-3])
print(List[:-1])
print(List[-3:-1])

5
3
[1, 2, 3, 4]
[3, 4]

In [10]:
#Updating list items
List = [1, 2, 3, 4, 5]
List[1] = 10
print(List)

[1, 10, 3, 4, 5]

In [11]:
#Updating multiple items
List = [1, 2, 3, 4, 5]
List[1:3] = [20,30]
print(List)

[1, 20, 30, 4, 5]

In [12]:
#Append items to a list
fruits = ["Apple", "Banana", "Cherry","kiwi","mango","orange"]
fruits.append("grape")
print(fruits)

['Apple', 'Banana', 'Cherry', 'kiwi', 'mango', 'orange', 'grape']

In [13]:
#insert items to a list
fruits = ["Apple", "Banana", "Cherry","kiwi","mango","orange"]
fruits.insert(2,"watermelon")
print(fruits)

['Apple', 'Banana', 'watermelon', 'Cherry', 'kiwi', 'mango', 'orange']

In [14]:
#remove items from a list
fruits = ["Apple", "Banana", "Cherry","kiwi","mango","orange"]
fruits.remove("Banana")
print(fruits)

['Apple', 'Cherry', 'kiwi', 'mango', 'orange']

In [15]:
#remove items at a specified index
fruits = ["apple", "banana", "cherry","kiwi","mango","orange"]
fruits.pop(2)
print(fruits)

['apple', 'banana', 'kiwi', 'mango', 'orange']

In [2]:
#Tuple 
thistuple = ("apple", "banana", "cherry", "banana")
print(thistuple)

('apple', 'banana', 'cherry', 'banana')

In [3]:
#length of tuple
thistuple = ("apple", "banana", "cherry")
print(len(thistuple))

3

In [5]:
#A tuple with one item - needs to have a comma if lacking one it becomes a string
thistuple = ("apple",)
print(type(thistuple))

#Accessing tuple items
thistuple = ("apple", "banana", "cherry")
print(thistuple[1])

<class 'tuple'>
banana

In [6]:
#range of indexes
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:5])

('cherry', 'orange', 'kiwi')

In [7]:
#Adding items to a tuple
#Tuples are unchangeable, so you cannot add items to it. However, you can convert the tuple into a list, add the item, and convert it back into a tuple.
thistuple = ("apple", "banana", "cherry")
mylist = list(thistuple)
mylist.append("orange")
thistuple = tuple(mylist)
print(thistuple)

('apple', 'banana', 'cherry', 'orange')

In [8]:
#Add tuple to a tuple
thistuple1 = ("apple", "banana", "cherry")

#Add to tuple with one item
thistuple2 = ("orange",)
thistuple1 += thistuple2
print(thistuple1)

('apple', 'banana', 'cherry', 'orange')

In [9]:
#remove the last item
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.remove("cherry")
print(y)

['apple', 'banana']

In [11]:
#Sets 
thisset = {"apple", "banana", "cherry"}
print(thisset)

#Duplicates are not allowed in sets
thisset = {"apple", "banana", "cherry", "apple"}
print(thisset)

{'banana', 'cherry', 'apple'}
{'banana', 'cherry', 'apple'}

In [12]:
#Access set items
thisset = {"apple", "banana", "cherry"}
for x in thisset:
    print(x)

banana
cherry
apple

In [13]:
#Adding items to a set - you cannot change items in a set but you can add
thisset = {"apple", "banana", "cherry"}
thisset.add("orange")
print(thisset)

{'orange', 'banana', 'cherry', 'apple'}

In [14]:
#Add elements from tropical to this set
thisset = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}
thisset.update(tropical)
print(thisset)

{'mango', 'banana', 'papaya', 'cherry', 'apple', 'pineapple'}

In [15]:
#Remove set items
thisset = {"apple", "banana", "cherry"}
thisset.remove("banana")
print(thisset)

{'cherry', 'apple'}

In [16]:
#Discard method to remove an item
thisset = {"apple", "banana", "cherry"}
thisset.discard("banana")
print(thisset)

{'cherry', 'apple'}

In [ ]:
#pop method to remove a random item   -removes a random item
thisset = {"apple", "banana", "cherry"}
thisset.pop()
print(thisset)

{'cherry', 'apple'}

In [21]:
#pop method to remove a random item
thisset = {"apple", "banana", "cherry" , "kiwi" , "mango"}
thisset.pop()
print(thisset)

{'banana', 'cherry', 'apple', 'kiwi'}

In [7]:
#creating a dictionary
thisdict = {"brand": "Ford", "model": "Mustang", "year": 1964}
print(thisdict)

#Dictionary length
thisdict = {
    "brand": "Ford",
      "model": "Mustang", 
        "year": 1964,
          "color": "red"}
print(len(thisdict))

#Get keys in a dictionary
thisdict = {
    "brand": "Ford", 
            "model": "Mustang",
              "year": 1964,
              "color": "red"}
#get a list of the keys
x = thisdict.keys()
print(x)

#get dictionary values
thisdict = {
    "brand": "Ford",
      "model": "Mustang",
        "year": 1964,
          "color": "red"}
#get a list of the values
y = thisdict.values()
print(y)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
4
dict_keys(['brand', 'model', 'year', 'color'])
dict_values(['Ford', 'Mustang', 1964, 'red'])

In [10]:
#changing values in a dictionary
thisdict = {
    "brand": "Ford",
      "model": "Mustang",
        "year": 1964,
          "color": "red"}
thisdict["year"] = 2020
print(thisdict)

#update dictionary
thisdict = {
    "brand": "Ford",
      "model": "Mustang",
        "year": 1964,
          "color": "red"}
thisdict.update({"color": "blue"})
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2020, 'color': 'red'}
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'blue'}

In [12]:
#Adding items to a dictionary
thisdict = {
    "brand": "Ford",
      "model": "Mustang",
        "year": 1964}
thisdict["color"] = "red"
thisdict["price"] = 35000
thisdict["owner"] = "Lisa"
print(thisdict)

#Remove items from a dictionary
thisdict = {
    "brand" : "Ford",
      "model": "Mustang",
        "year": 1964,
          "color": "red"}
thisdict.pop("model")
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red', 'price': 35000, 'owner': 'Lisa'}
{'brand': 'Ford', 'year': 1964, 'color': 'red'}

In [ ]:
#pop item to remove items in a dictonary
thisdict = {
    "brand" : "Ford",
      "model": "Mustang",
        "year": 1964,
          "color": "red"}
thisdict.popitem()
print(thisdict)

#Delete key to remove items in a dictonary
thisdict = {
    "brand" : "Ford",
      "model": "Mustang",
        "year": 1964,
          "color": "red"}
del thisdict
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [1]:
#If else
a=33
b=200
if b >a :
  print("b is greater than a")

b is greater than a

In [2]:
#Elif
a=33
b=200
if b >a :
  print("b is greater than a")
elif a ==b :
  print("a and b are equal")

b is greater than a

In [3]:
#Else
a=200
b=33
if b >a :
  print("b is greater than a")
else :
    print("b is not greater than a")

b is not greater than a

In [4]:
#short hand if
if a>b: print("a is greater than b")

#short hand if else
a=2
b=330
print("A") if a>b else print("B")

#multiple else if statements on same line
a=3300
b=33000
print("A") if a>b else print("=") if a==b else print("B")

a is greater than b
B
B

In [5]:
#And
a=200
b=33
c=500
if a>b and c>a:
  print("Both conditions are True")

Both conditions are True

In [6]:
#or
a=200
b=33
c=500
if a>b or a>c:
  print("At least one of the conditions is True")

At least one of the conditions is True

In [7]:
#nested if
x=41
if x>10:
    print("Above ten,")
    if x>20:
        print("and also above 20!")
    else:
        print("but not above 20")

Above ten,
and also above 20!

In [8]:
#Check number is positive
num=float(input("Enter a number:"))
if num>=0:
    if num==0:
        print("Zero")
    else:
        print("Positive number")
else:
    print("Negative number")

Positive number

In [9]:
# pass statement
a=33
b=200
if b>a:
    pass
list=[4,3,5,6,7]
if list [0]>list[1]:
    print("success")
else:
    print("hello")

success

In [10]:
#Python while loops
i=1
while i<6:
    print(i)
    i +=1

1
2
3
4
5

In [2]:
#The break Statement
i=1
while i<6:
    print(i)
    if i==3:
        break
    i +=1

1
2
3

In [1]:
#The continue Statement
i=0
while i<6:
    i +=1
    if i==3:
        continue
    print(i)

1
2
4
5
6

In [12]:
#The else statement
i=1
while i<6:
    print(i)
    i +=1
else:
    print("i is no longer less than 6")

    list=[4,3,5,6,7]
    s=5
    i=0
    while i < len(list):
        if list[i]==s:
            print("found successfully")
            break
        i +=1
    else:
        print("no match found")

1
2
3
4
5
i is no longer less than 6
found successfully

In [2]:
#Python for loops
fruits=["Apple","banana","cherry"]
for x in fruits:
    print(x)

    for x in "banana":
        print(x)

Apple
b
a
n
a
n
a
banana
b
a
n
a
n
a
cherry
b
a
n
a
n
a

In [4]:
#Break statement
fruits=["Apple","banana","cherry"]
for x in fruits:
    print(x)
    if x =="banana":
        break

Apple
banana

In [5]:
#Continue statement
fruits=["Apple","banana","cherry"]
for x in fruits:
    if x =="banana":
        continue
    print(x)

Apple
cherry

In [9]:
#range() function
for x in range (6):

   print(x)

   for x in range(2,6):
      print(x)

0
2
3
4
5
1
2
3
4
5
2
2
3
4
5
3
2
3
4
5
4
2
3
4
5
5
2
3
4
5

In [10]:
#nested loops
adj=["red","big","tasty"]
fruits=["apple","banana","cherry"]
for x in adj:
    for y in fruits:
        print(x,y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry

In [4]:
#The pass statement
#program to find the strings in list are even or odd
even=["red","blue","green"]
for x in even:
    if len(x)%2==0:
        print("even string")
    else:
        print(x,"odd string")

red odd string
even string
green odd string

In [5]:
#complete distance between two points
x1=int(input("Enter x1:"))
x2=int(input("Enter x2:"))
y1=int(input("Enter y1:"))
y2=int(input("Enter y2:"))
result=((((x2-x1)**2)+((y2-y1)**2))**0.5)
print("Distance between points", (x1,y1), "and", (x2,y2), "is", result)

Distance between points (45, 56) and (67, 98) is 47.41307836451879

In [16]:
#python program to check if the input number is odd or even
num=int(input("enter a number:"))
if num%2==0:
    print("{0} is Even".format(num))
else:
    print("{0} is odd".format(num))

34 is Even

In [18]:
#python program to swap two variables
p=int(input("Please enter value for p :"))
q=int(input("please  enter value for q :"))
temp=p
p=q
q=temp
print("value of p after swapping :",p)
print("value of q after swapping :" ,q)

value of p after swapping : 78
value of q after swapping : 23

In [21]:
#find factorial of a number
num=int(input("enter a number:"))
factorial=1
if num < 0:
    print(" factorial does not exist for negative numbers")
elif num ==0:
    print("The factorial of 0 is 1 ")
else:
    for i in range(1,num+1):
        factorial=factorial*i
        print("The factorial of", num , "is", factorial)

The factorial of 5 is 1
The factorial of 5 is 2
The factorial of 5 is 6
The factorial of 5 is 24
The factorial of 5 is 120

In [7]:
#simple function
def myfunction():
    print("Hello from a function")
myfunction()

Hello from a function

In [3]:
#Arguments in a function
def OddEven(num=10):
    if num%2==0:
        print("{0} is Even".format(num))
    else:
        print("{0} is odd".format(num))

OddEven(15)

15 is odd

In [4]:
#Functions with a return statement
def myfunction(x):
    return 5*x
print(myfunction(3))

15

In [5]:
# return statement
def square_value(num):
    """This function returns the square value of the entered number"""
    return num**2
print(square_value(2))
print(square_value(-4))

4
16

In [6]:
def my_function(food):
    for x in food:
        print(x)
fruits = ["apple", "banana", "cherry"]

my_function(fruits)

apple
banana
cherry

In [1]:
#Opening a file
f = open ("STUDENTS.txt", "r")
print(f.read())

Name	Age	Major	Hobby	Gender	ID number
Lisa	67	DSA	reading	Female	450
Victor	23	APT	baking	Male	345
Wanjiru	14	IBA	swimming	Female	565
Wenza	19	IST	cooking	Male	777
Zabiba	18	IR	painting	Female	890

In [2]:
#Writing in a file
f = open("STUDENTS.txt", "w")
f.write("Hello, this is a test file.")
f.close()

In [3]:
#Append to a file
f = open("STUDENTS.txt", "a")
f.write("\nThis is an additional line.")
f.close()

In [4]:
#Read only a part of the file
f = open("STUDENTS.txt", "r")
print(f.read(10))

Hello, thi

In [5]:
#Read line by line
f = open("STUDENTS.txt", "r")
print(f.readline())

Hello, this is a test file.

In [1]:
# Zero divivion exception
try :
    x = 5 / 0
except ZeroDivisionError:
    print("You cannot divide by zero!")

You cannot divide by zero!

In [2]:
#try - except statement
try :
    x = 5 / 0
except (ZeroDivisionError, TypeError):
    print("An error occured: division by zero or wrong data type")

An error occured: division by zero or wrong data type

In [3]:
#Try except with else
try :
    x = 6 / 7
except ZeroDivisionError :
    print("You cannot divide by zero!")
else:
    print(f"Result is {x}")

Result is 0.8571428571428571

In [4]:
#Except statement with no exception
try :
    x= 5 / 0
except ZeroDivisionError:
    print("You cannot divide by zero!")

You cannot divide by zero!

In [5]:
#ID Error
try:
    f = open("nonexistentfile.txt", "r")
except FileNotFoundError:
    print("An error occured trying to read the file")

An error occured trying to read the file

In [6]:
#Try except , else and finally
try :
    x = 5 / 0
except ZeroDivisionError:
    print("You cannot divide by zero!")
finally:
    print("This will always be executed")

You cannot divide by zero!
This will always be executed

In [3]:
#Reading a csv file with DictReader
import csv
with open('students.csv', mode='r') as cvsfile:
    m=list(csv.DictReader(cvsfile))
    print(m)

[{'Name': 'Lisa', 'Age': '67', 'Major': 'DSA', 'Hobby': 'reading', 'Gender': 'Female', 'ID number': '450', '': ''}, {'Name': 'Victor', 'Age': '23', 'Major': 'APT', 'Hobby': 'baking', 'Gender': 'Male', 'ID number': '345', '': ''}, {'Name': 'Wanjiru', 'Age': '14', 'Major': 'IBA', 'Hobby': 'swimming', 'Gender': 'Female', 'ID number': '565', '': ''}, {'Name': 'Wenza', 'Age': '19', 'Major': 'IST', 'Hobby': 'cooking', 'Gender': 'Male', 'ID number': '777', '': ''}, {'Name': 'Zabiba', 'Age': '18', 'Major': 'IR', 'Hobby': 'painting', 'Gender': 'Female', 'ID number': '890', '': ''}]

In [4]:
#creating a cvs file with reader
import csv
with open('students.csv', mode='r') as csvfile:
    m=list(csv.reader(csvfile))
    print(m)

[['Name', 'Age', 'Major', 'Hobby', 'Gender', 'ID number', ''], ['Lisa', '67', 'DSA', 'reading', 'Female', '450', ''], ['Victor', '23', 'APT', 'baking', 'Male', '345', ''], ['Wanjiru', '14', 'IBA', 'swimming', 'Female', '565', ''], ['Wenza', '19', 'IST', 'cooking', 'Male', '777', ''], ['Zabiba', '18', 'IR', 'painting', 'Female', '890', '']]

In [5]:
#writing to a csv file with DictWriter
import csv
with open('students.csv', mode='w', newline='') as csvfile:
    fieldnames = ['name', 'age', 'major','Hobbies','gender','idnumber']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerow({'name': 'Jena', 'age': 20, 'major': 'Computer Science', 'Hobbies': 'Reading', 'gender': 'Female', 'idnumber': 1})
    writer.writerow({'name': 'Piper', 'age': 22, 'major': 'Mathematics', 'Hobbies': 'Swimming', 'gender': 'Female', 'idnumber': 2})

In [6]:
#Loop through rows in a csv file
import csv
with open('students.csv', mode='r') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        print(row)

{'name': 'Jena', 'age': '20', 'major': 'Computer Science', 'Hobbies': 'Reading', 'gender': 'Female', 'idnumber': '1'}
{'name': 'Piper', 'age': '22', 'major': 'Mathematics', 'Hobbies': 'Swimming', 'gender': 'Female', 'idnumber': '2'}

In [8]:
#create  a series with pandas
import pandas as pd
data = ["John","Lisa","Wambo","Issa"]
s = pd.Series(data)
print(s)

0     John
1     Lisa
2    Wambo
3     Issa
dtype: object

In [9]:
#creating a series with custom index
import pandas as pd
data = ["John","Lisa","Wambo","Issa"]
index = ["a", "b", "c", "d"]
series = pd.Series(data, index=index)
print(series)

a     John
b     Lisa
c    Wambo
d     Issa
dtype: object

In [10]:
#using a dictionary to create a series
import pandas as pd
data = {"Physics": 85, "Math": 90, "Chemistry": 78}
series = pd.Series(data)
print(series)

Physics      85
Math         90
Chemistry    78
dtype: int64

In [12]:
#printing the index and values of a series
import pandas as pd
data = {"Physics":85, "Math": 90, "Chemistry": 78}
s = pd.Series(data)
print(s.index)
print(s.values)

Index(['Physics', 'Math', 'Chemistry'], dtype='object')
[85 90 78]

In [15]:
##none vs NaN
import pandas as pd
names =[None, "John", "Lisa", "Wambo", "Issa"]
series = pd.Series(names)
print(series)

0     None
1     John
2     Lisa
3    Wambo
4     Issa
dtype: object

In [16]:
#None vs NaN
import pandas as pd
numbers = [1,2,3,None,5]
series = pd.Series(numbers)
print(series)

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64

In [1]:
#Querying a series with iloc
import pandas as pd
data ={"physics":85,"math":90,"chemistry":78,"biology":92}
s = pd.Series(data)
print(s.iloc[1])

90

In [2]:
#Querying a series using loc
import pandas as pd
data ={"physics":85,"math":90,"chemistry":78,"biology":92}
s = pd.Series(data)
print(s.loc["math"])

90

In [4]:
#Creating a DataFrame by passing a numpphy array
import pandas as pd
import numpy as np
dates = pd.date_range("20230601", periods=6)
dates
df = pd.DataFrame(np.random.rand(6,4), index=dates, columns=["A","B","C","D"])
df

                   A         B         C         D
2023-06-01  0.743760  0.490534  0.784721  0.937481
2023-06-02  0.347500  0.326373  0.049670  0.346623
2023-06-03  0.725171  0.396271  0.160567  0.417586
2023-06-04  0.277080  0.655176  0.531407  0.843976
2023-06-05  0.917931  0.028500  0.206283  0.954270
2023-06-06  0.651694  0.917242  0.713331  0.782240

In [5]:
#creating a DataFrame
import pandas as pd
data = {
    "Name": ["John", "Lisa", "Wambo", "Issa"],
    "Age": [20, 22, 21, 23],
    "Major": ["Computer Science", "Mathematics", "Physics", "Chemistry"],
    "Hobbies": ["Reading", "Swimming", "Gaming", "Cooking"],
}
df = pd.DataFrame(data)
print(df)

    Name  Age             Major   Hobbies
0   John   20  Computer Science   Reading
1   Lisa   22       Mathematics  Swimming
2  Wambo   21           Physics    Gaming
3   Issa   23         Chemistry   Cooking

In [6]:
#Querying a dataframe using loc
import pandas as pd
data = {
    "Name": ["John", "Lisa", "Wambo", "Issa"],
    "Age": [20, 22, 21, 23],
    "Major": ["Computer Science", "Mathematics", "Physics", "Chemistry"],
    "Hobbies": ["Reading", "Swimming", "Gaming", "Cooking"],
}
df = pd.DataFrame(data)
print(df.loc[3])
print(df.loc[1:3])
print(df.loc[df["Age"] > 21])
print(df.loc[df["Major"] == "Physics"])

Name            Issa
Age               23
Major      Chemistry
Hobbies      Cooking
Name: 3, dtype: object
    Name  Age        Major   Hobbies
1   Lisa   22  Mathematics  Swimming
2  Wambo   21      Physics    Gaming
3   Issa   23    Chemistry   Cooking
   Name  Age        Major   Hobbies
1  Lisa   22  Mathematics  Swimming
3  Issa   23    Chemistry   Cooking
    Name  Age    Major Hobbies
2  Wambo   21  Physics  Gaming

In [7]:
#Rename columns in a DataFrame
import pandas as pd
data = {
    "Name": ["John", "Lisa", "Wambo", "Issa"],
    "Age": [20, 22, 21, 23],
    "Major": ["Computer Science", "Mathematics", "Physics", "Chemistry"],
    "Hobbies": ["Reading", "Swimming", "Gaming", "Cooking"],
}
df = pd.DataFrame(data)
df.rename(columns={"Name": "Full Name", "Age": "Years Old"}, inplace=True)
print(df)

  Full Name  Years Old             Major   Hobbies
0      John         20  Computer Science   Reading
1      Lisa         22       Mathematics  Swimming
2     Wambo         21           Physics    Gaming
3      Issa         23         Chemistry   Cooking

In [8]:
#Dropping columns in a DataFrame
import pandas as pd
data = {
    "Name": ["John", "Lisa", "Wambo", "Issa"],
    "Age": [20, 22, 21, 23],
    "Major": ["Computer Science", "Mathematics", "Physics", "Chemistry"],
    "Hobbies": ["Reading", "Swimming", "Gaming", "Cooking"],
}
df = pd.DataFrame(data)
df.drop('Age', axis=1, inplace=True)
df.columns

Index(['Name', 'Major', 'Hobbies'], dtype='object')

In [9]:
#Querying a dataframe column
import pandas as pd
data = {
    "Name": ["John", "Lisa", "Wambo", "Issa"],
    "Age": [20, 22, 21, 23],
    "Major": ["Computer Science", "Mathematics", "Physics", "Chemistry"],
    "Hobbies": ["Reading", "Swimming", "Gaming", "Cooking"],
}
df = pd.DataFrame(data)
print(df["Age"]<22)

0     True
1    False
2     True
3    False
Name: Age, dtype: bool

In [5]:
#Extracting values from a dataframe
df.loc["shop2"]

      student  Purchase  cost
shop2    Lisa       pen    70
shop2   Wambo  notebook    20

In [6]:
df.loc["shop2", "student"]

shop2     Lisa
shop2    Wambo
Name: student, dtype: object

In [8]:
df.loc[:,["cost","student"]]

       cost student
shop1    30    John
shop2    70    Lisa
shop2    20   Wambo

In [9]:
df.loc["place"]=["mall","road","chowk"]
df

      student  Purchase   cost
shop1    John    pencil     30
shop2    Lisa       pen     70
shop2   Wambo  notebook     20
place    mall      road  chowk

In [10]:
#Rename a column
df.rename(columns={"place":"location","student":"students"})

      students  Purchase   cost
shop1     John    pencil     30
shop2     Lisa       pen     70
shop2    Wambo  notebook     20
place     mall      road  chowk

In [ ]:
#Inplace
df.rename(columns={"place":"location","student":"students"}, inplace=True)
df.columns

In [7]:
#Creating a dataset to demonstrate groupby
import pandas as pd
data = {
    "Name": ["John", "Jane","Doe", "Smith", "Jazmin"],
    "Age": [25, 30, 35, 40, 45],
    "Major": ["Computer","Science","engineering","mathematics","physics"],
    "Hobbies":["reading","sports","music","Travelling","swimming"],
    "GPA":[3.5, 3.8, 3.2, 3.9, 3.6  ],
    "Gender":["Male","Female","Male","Male","Female"],
    "Height" : [1.75,1.65,1.80,1.70,1.60]

}
df= pd.DataFrame(data)

#group by major and calculate mean GPA
grouped = df.groupby("Major")["GPA"].mean()
print(grouped)

Major
Computer       3.5
Science        3.8
engineering    3.2
mathematics    3.9
physics        3.6
Name: GPA, dtype: float64

In [3]:
#aggregations with multiple functions
import  pandas as pd
data = {"Name": ["John", "Jane","Doe", "Smith", "Jazmin"],
    "Age": [25, 30, 35, 40, 45],
    "Major": ["Computer","Science","engineering","mathematics","physics"],
    "Hobbies":["reading","sports","music","Travelling","swimming"],
    "Gender":["Male","Female","Male","Male","Female"],
    "Height" : [1.75,1.65,1.80,1.70,1.60],
     "GPA":[3.5, 3.8, 3.2, 3.9, 3.6  ]
}
df = pd.DataFrame(data)
grouped = df.groupby("Major")["GPA"].agg(["mean", "min", "max"])
print(grouped)

             mean  min  max
Major
Computer      3.5  3.5  3.5
Science       3.8  3.8  3.8
engineering   3.2  3.2  3.2
mathematics   3.9  3.9  3.9
physics       3.6  3.6  3.6

In [7]:
#Scales
#Nominal scale
import csv
import pandas as pd
df=pd.DataFrame(['A+','A-','B-','B+','C-','C+'],index=['excellent','excellent','good','good','ok','ok'])
df.rename(columns={0:'grades'}, inplace=True)
a = df['grades'].astype('category').head()
print(a)

excellent    A+
excellent    A-
good         B-
good         B+
ok           C-
Name: grades, dtype: category
Categories (6, object): ['A+', 'A-', 'B+', 'B-', 'C+', 'C-']

In [11]:
#Ordinal scale
import csv
import pandas as pd
df=pd.DataFrame(['A+','A-','B-','B+','C-','C+'],index=['excellent','excellent','good','good','ok','ok'])
df.rename(columns={0:'grades'}, inplace=True)
grades = pd.Categorical(df['grades'], categories=['A+','A-','B-','B+','C-','C+'], ordered=True)
print(grades)

['A+', 'A-', 'B-', 'B+', 'C-', 'C+']
Categories (6, object): ['A+' < 'A-' < 'B-' < 'B+' < 'C-' < 'C+']

In [10]:
#Simulate car dataset to create a pivot table
import pandas as pd
data = {
    "Car": ["Toyota", "Honda", "Ford", "Toyota", "Honda", "Ford"],
    "Year": [2020, 2020, 2020, 2021, 2021, 2021],
    "Sales": [100, 150, 200, 120, 180, 220]
}
df = pd.DataFrame(data)
pivot_table = df.pivot_table(values='Sales', index='Car', columns='Year', aggfunc='sum')
print(pivot_table)

Year    2020  2021
Car
Ford     200   220
Honda    150   180
Toyota   100   120

In [16]:
#Data functionality in pandas
#Timestamp

import pandas as pd
import numpy as np
pd.Timestamp('2024-01-01')
pd.Timestamp('2024-01-01 12:30:45')

Timestamp('2024-01-01 12:30:45')

In [13]:
#period example
pd.Period('2024-01')
pd.Period('2024-01-01')
pd.Period('/2024')

Period('2024', 'Y-DEC')

In [ ]:
#Dta functionality in pandas
#Datetime index